#!/bin/bash
export LOAD_MEGABYTES=50
export MEGABYTES_INCREASE_PER_LOAD=50
export LOAD_DURATION_SECONDS=10
export SECONDS_BETWEEN_LOADS=10
export SECONDS_INCREASE_PER_LOAD=1
export TOTAL_TEST_DURATION_SECONDS=120
